# In a nutshell, this workflow allows Github Action to
# automatically, based on a schedule, update the 
# SECRET_KEY in .env, based on the 
# generate-secret-key.js script. It then also
# pushes the new key to main.

name: Rotate Secret Key

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at 00:00
# <minute> <hour> <day of month> <month> <day of week>
#  0-59     0-23      1-31        1-12    0-7 (Sunday = 0 or 7)   

# 0 3 * * *    would run the command every day at 3:00 AM.
# */15 * * * * would run the command every 15 minutes.
# 0 0 * * 1    would run the command every Monday at midnight.
# 0 0 1 * *    would run the command at midnight on the first day of every month

# Each field must contain a valid numerical value or one of the
# special characters (* / - ,). Be cautious with the time zone differences when
# scheduling cron jobs, as they run based on the system's local time zone.

jobs:
  rotate-key:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # latest 18.x version

      - name: Generate New Secret Key
        run: node generate-secret-key.js
        id: secretKey

      - name: Update GitHub Secret
        run: echo "SECRET_KEY=${{ steps.secretKey.outputs.stdout }}" >> $GITHUB_ENV
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -am "Update secret key"
          git push

